import { Car, Office } from "@/types/car";

export const offices: Office[] = [
  {
    city_ua: "Київ",
    city_ru: "Киев",
    city_en: "Kyiv",
    address_ua: "вул. Голосіївська, 11",
    address_ru: "ул. Голосеевская, 11",
    address_en: "11 Holosiivska St.",
    phones: ["+380966789000", "+380996789000"],
  },
  {
    city_ua: "Одеса",
    city_ru: "Одесса",
    city_en: "Odesa",
    address_ua: "вул. Чорноморського Козацтва, 23",
    address_ru: "ул. Черноморского Казачества, 23",
    address_en: "23 Chornomorskoho Kozatstva St.",
    phones: ["+380966789000"],
  },
  {
    city_ua: "Львів",
    city_ru: "Львов",
    city_en: "Lviv",
    address_ua: "вул. Пасічна, 129А",
    address_ru: "ул. Пасечная, 129А",
    address_en: "129A Pasichna St.",
    phones: ["+380966789000"],
  },
  {
    city_ua: "Харків",
    city_ru: "Харьков",
    city_en: "Kharkiv",
    address_ua: "просп. Науки, 25",
    address_ru: "просп. Науки, 25",
    address_en: "25 Nauky Ave.",
    phones: ["+380966789000"],
  },
  {
    city_ua: "Дніпро",
    city_ru: "Днепр",
    city_en: "Dnipro",
    address_ua: "вул. Запорізьке шосе, 53б",
    address_ru: "ул. Запорожское шоссе, 53б",
    address_en: "53b Zaporizke Hwy.",
    phones: ["+380966789000"],
  },
  {
    city_ua: "Вінниця",
    city_ru: "Винница",
    city_en: "Vinnytsia",
    address_ua: "вул. Немирівське шосе, 94",
    address_ru: "ул. Немировское шоссе, 94",
    address_en: "94 Nemyrivske Hwy.",
    phones: ["+380966789000"],
  },
  {
    city_ua: "Ужгород",
    city_ru: "Ужгород",
    city_en: "Uzhhorod",
    address_ua: "вул. Митрака, 5",
    address_ru: "ул. Митрака, 5",
    address_en: "5 Mytraka St.",
    phones: ["+380966789000"],
  },
  {
    city_ua: "Кропивницький",
    city_ru: "Кропивницкий",
    city_en: "Kropyvnytskyi",
    address_ua: "вул. Академіка Тамма, 33/32",
    address_ru: "ул. Академика Тамма, 33/32",
    address_en: "33/32 Akademika Tamma St.",
    phones: ["+380966789000"],
  },
];

export const initialCars: Car[] = [
  {
    id: "1",
    slug: "byd-song-plus-ev-520km-premium-2024",
    brand: "BYD",
    model: "Song Plus EV 520KM Premium",
    year: 2024,
    price_usd: 26000,
    price_uah: 1073000,
    range_km: 505,
    battery_kwh: 71.8,
    power_hp: 184,
    acceleration_0_100: 8.5,
    trim: "",
    drive_type: "FWD",
    body_type: "EV",
    color: "Grey",
    mileage_km: 0,
    status: "in_stock",
    is_new: true,
    is_visible: true,
    description_ua:
      "BYD Song Plus EV — сучасний електричний SUV з технологією Blade Battery. Простора кабіна, передові системи безпеки та вражаючий запас ходу.",
    description_ru:
      "BYD Song Plus EV — современный электрический SUV с технологией Blade Battery. Просторный салон, передовые системы безопасности и впечатляющий запас хода.",
    images: [
      "https://electro-motors.top/image/cache/catalog/emfotoecar/byd/songplusev/songplusev1-1000x562.jpeg",
    ],
    thumbnail:
      "https://electro-motors.top/image/cache/catalog/emfotoecar/byd/songplusev/songplusev1-1000x562.jpeg",
    specs: {
      seats: 5,
      trunk_liters: 574,
      max_speed_kmh: 170,
      charge_time_fast: "30 хв (30-80%)",
      charge_time_slow: "8 год",
      warranty_years: 3,
      features: [
        "Blade Battery",
        "360° камера",
        "Adaptive Cruise Control",
        "Панорамний дах",
        "Шкіряний салон",
      ],
    },
    created_at: "2024-01-01",
    archived_at: null,
    updated_at: "2024-01-01",
  },
  {
    id: "2",
    slug: "volkswagen-id4-crozz-pure-plus-2024",
    brand: "Volkswagen",
    model: "ID.4 Crozz Pure+",
    year: 2024,
    price_usd: 28500,
    price_uah: 1176000,
    range_km: 550,
    battery_kwh: 84.8,
    power_hp: 204,
    acceleration_0_100: 8.2,
    trim: "",
    drive_type: "RWD",
    body_type: "EV",
    color: "White",
    mileage_km: 0,
    status: "in_stock",
    is_new: true,
    is_visible: true,
    description_ua:
      "Volkswagen ID.4 Crozz — преміальний електрокросовер від німецького концерну. Відмінна якість збірки, інтуїтивний інтерфейс та великий запас ходу.",
    description_ru:
      "Volkswagen ID.4 Crozz — премиальный электрокроссовер от немецкого концерна. Отличное качество сборки, интуитивный интерфейс и большой запас хода.",
    images: [
      "https://electro-motors.top/image/cache/catalog/electrocars/id4/vw-id4-pure-7-1000x562.jpg",
    ],
    thumbnail:
      "https://electro-motors.top/image/cache/catalog/electrocars/id4/vw-id4-pure-7-1000x562.jpg",
    specs: {
      seats: 5,
      trunk_liters: 543,
      max_speed_kmh: 160,
      charge_time_fast: "38 хв (5-80%)",
      charge_time_slow: "7.5 год",
      warranty_years: 3,
      features: [
        "ID. Light",
        "Travel Assist",
        "Панорамний дах",
        "Wireless CarPlay",
        "Matrix LED",
      ],
    },
    created_at: "2024-01-01",
    archived_at: null,
    updated_at: "2024-01-01",
  },
  {
    id: "3",
    slug: "honda-mn-v-basic-2024",
    brand: "Honda",
    model: "MN-V Basic",
    year: 2024,
    price_usd: 18500,
    price_uah: 763000,
    range_km: 480,
    battery_kwh: 61.3,
    power_hp: 163,
    acceleration_0_100: 9.4,
    trim: "",
    drive_type: "FWD",
    body_type: "EV",
    color: "Blue",
    mileage_km: 0,
    status: "in_stock",
    is_new: true,
    is_visible: true,
    description_ua:
      "Honda MN-V — компактний електричний кросовер з надійною японською якістю. Ідеальний варіант для міста з хорошим запасом ходу.",
    description_ru:
      "Honda MN-V — компактный электрический кроссовер с надёжным японским качеством. Идеальный вариант для города с хорошим запасом хода.",
    images: [
      "https://electro-motors.top/image/cache/catalog/electrocars/m-nv/mnv-base-1000x562.jpg",
    ],
    thumbnail:
      "https://electro-motors.top/image/cache/catalog/electrocars/m-nv/mnv-base-1000x562.jpg",
    specs: {
      seats: 5,
      trunk_liters: 437,
      max_speed_kmh: 140,
      charge_time_fast: "35 хв (30-80%)",
      charge_time_slow: "9 год",
      warranty_years: 2,
      features: [
        "Honda Sensing",
        "LED фари",
        "Сенсорний дисплей 8\"",
        "Камера заднього виду",
      ],
    },
    created_at: "2024-01-01",
    archived_at: null,
    updated_at: "2024-01-01",
  },
  {
    id: "4",
    slug: "zeekr-001-you-100kwh-2024",
    brand: "Zeekr",
    model: "001 YOU 100kWh",
    year: 2024,
    price_usd: 42000,
    price_uah: 1733000,
    range_km: 656,
    battery_kwh: 100,
    power_hp: 544,
    acceleration_0_100: 3.8,
    trim: "",
    drive_type: "AWD",
    body_type: "EV",
    color: "Black",
    mileage_km: 0,
    status: "in_stock",
    is_new: true,
    is_visible: true,
    description_ua:
      "Zeekr 001 — флагманський електромобіль від преміального бренду Geely. Неймовірна динаміка, розкішний салон та максимальний запас ходу.",
    description_ru:
      "Zeekr 001 — флагманский электромобиль от премиального бренда Geely. Невероятная динамика, роскошный салон и максимальный запас хода.",
    images: [
      "https://electro-motors.top/image/cache/catalog/electrocars/m-nv/mnv-base-1000x562.jpg",
    ],
    thumbnail:
      "https://electro-motors.top/image/cache/catalog/electrocars/m-nv/mnv-base-1000x562.jpg",
    specs: {
      seats: 5,
      trunk_liters: 560,
      max_speed_kmh: 200,
      charge_time_fast: "25 хв (10-80%)",
      charge_time_slow: "6.5 год",
      warranty_years: 3,
      features: [
        "Air Suspension",
        "Yamaha Audio 15 динаміків",
        "Автопілот NZP",
        "HUD дисплей",
        "Електричні двері",
        "Frameless двері",
      ],
    },
    created_at: "2024-01-01",
    archived_at: null,
    updated_at: "2024-01-01",
  },
  {
    id: "5",
    slug: "avatr-07-fwd-2025",
    brand: "Avatr",
    model: "07 FWD",
    year: 2025,
    price_usd: 35000,
    price_uah: 1444000,
    range_km: 621,
    battery_kwh: 92,
    power_hp: 295,
    acceleration_0_100: 5.9,
    trim: "",
    drive_type: "FWD",
    body_type: "EV",
    color: "White",
    mileage_km: 0,
    status: "on_order",
    is_new: true,
    is_visible: true,
    description_ua:
      "Avatr 07 — стильний електрокросовер спільного виробництва Huawei, CATL та Changan. Технологічно насичений автомобіль з розумною системою водіння.",
    description_ru:
      "Avatr 07 — стильный электрокроссовер совместного производства Huawei, CATL и Changan. Технологически насыщенный автомобиль с умной системой вождения.",
    images: [
      "https://electro-motors.top/image/cache/catalog/electrocars/m-nv/mnv-base-1000x562.jpg",
    ],
    thumbnail:
      "https://electro-motors.top/image/cache/catalog/electrocars/m-nv/mnv-base-1000x562.jpg",
    specs: {
      seats: 5,
      trunk_liters: 530,
      max_speed_kmh: 180,
      charge_time_fast: "20 хв (30-80%)",
      charge_time_slow: "7 год",
      warranty_years: 3,
      features: [
        "Huawei ADS 2.0",
        "Harmony OS",
        "CATL Qilin Battery",
        "AR HUD",
        "23 динаміки",
      ],
    },
    created_at: "2024-01-01",
    archived_at: null,
    updated_at: "2024-01-01",
  },
  {
    id: "6",
    slug: "byd-seal-premium-awd-2024",
    brand: "BYD",
    model: "Seal Premium AWD",
    year: 2024,
    price_usd: 34000,
    price_uah: 1403000,
    range_km: 520,
    battery_kwh: 82.5,
    power_hp: 530,
    acceleration_0_100: 3.8,
    trim: "",
    drive_type: "AWD",
    body_type: "EV",
    color: "Silver",
    mileage_km: 0,
    status: "in_stock",
    is_new: true,
    is_visible: true,
    description_ua:
      "BYD Seal — спортивний електроседан з технологією Cell-to-Body. Конкурент Tesla Model 3 з кращим оснащенням за нижчою ціною.",
    description_ru:
      "BYD Seal — спортивный электроседан с технологией Cell-to-Body. Конкурент Tesla Model 3 с лучшим оснащением по более низкой цене.",
    images: [
      "https://electro-motors.top/image/cache/catalog/emfotoecar/byd/songplusev/songplusev1-1000x562.jpeg",
    ],
    thumbnail:
      "https://electro-motors.top/image/cache/catalog/emfotoecar/byd/songplusev/songplusev1-1000x562.jpeg",
    specs: {
      seats: 5,
      trunk_liters: 400,
      max_speed_kmh: 180,
      charge_time_fast: "26 хв (30-80%)",
      charge_time_slow: "10 год",
      warranty_years: 3,
      features: [
        "Cell-to-Body",
        "iTAC",
        "Dynaudio Audio",
        "NFC ключ",
        "Вентильовані сидіння",
      ],
    },
    created_at: "2024-01-01",
    archived_at: null,
    updated_at: "2024-01-01",
  },
];

export const brands = [
  "Aplus",
  "Aspiring",
  "AUDI",
  "AVATR",
  "BAIC",
  "BLUESUN",
  "BMW",
  "Bosch",
  "BYD",
  "CHEVROLET",
  "Continental",
  "Convoy",
  "Cyclone",
  "DENZA",
  "DEYE",
  "Dongfeng",
  "Dotz",
  "Geely",
  "Honda",
  "JAC",
  "NIO",
  "Volkswagen",
  "Xpeng",
  "Zeekr",
];

export const bodyTypes = ["EV", "EREV", "PHEV"];

export const carYears = [
  2027, 2026, 2025, 2024, 2023, 2022, 2021, 2020, 2019, 2018,
  2017, 2016, 2015, 2014, 2013, 2012, 2011, 2010, 2009, 2008,
  2007, 2006, 2005, 2004, 2003, 2002, 2001, 2000,
];

export const carColors = [
  "—",
  "BLUE",
  "WHITE",
  "BLACK",
  "GREEN",
  "GRAY",
  "RED",
  "YELLOW",
  "ORANGE",
  "GOLD",
  "SILVER",
  "PURPLE",
  "BEIGE",
  "BROWN",
  "DARK GRAY",
  "SMOKY GRAY",
];
